//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KubeMob.Common.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KubeMob.Common.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears there is something wrong with the account we are using to connect to this cluster. Please check the account details.
        /// </summary>
        internal static string AccountInvalid_Message {
            get {
                return ResourceManager.GetString("AccountInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account issue.
        /// </summary>
        internal static string AccountInvalid_Title {
            get {
                return ResourceManager.GetString("AccountInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure.
        /// </summary>
        internal static string AddAccountPage_AddAzureAccount_Btn {
            get {
                return ResourceManager.GetString("AddAccountPage_AddAzureAccount_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string AddAccountPage_Title {
            get {
                return ResourceManager.GetString("AddAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID is required..
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientId_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientId_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientId_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a client ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientId_Placeholder {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is required..
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientSecret_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientSecret_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientSecret_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientSecret_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a client secret.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientSecret_Placeholder {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientSecret_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string AddEditAzureAccountPage_Environment_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Environment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a environment.
        /// </summary>
        internal static string AddEditAzureAccountPage_Environment_Title {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Environment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details for a service principal that has access to resources in your Microsoft Azure account. You can find out more about Service Princpial by tapping on the info button..
        /// </summary>
        internal static string AddEditAzureAccountPage_Help {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string AddEditAzureAccountPage_Information_ToolbarItem {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Information_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddEditAzureAccountPage_SaveButton {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID is required..
        /// </summary>
        internal static string AddEditAzureAccountPage_TenantId_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_TenantId_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_TenantId_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_TenantId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tenant ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_TenantId_Placeholder {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_TenantId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure account.
        /// </summary>
        internal static string AddEditAzureAccountPage_Title {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kubemob.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be a problem with this account.  Please update..
        /// </summary>
        internal static string AzureAccountManager_GetClusters_AuthenticationErrorMessage {
            get {
                return ResourceManager.GetString("AzureAccountManager_GetClusters_AuthenticationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing account already exists for this tenant..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_DuplicateTenantId {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_DuplicateTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client specified cannot be found..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_InvalidClientId {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is invalid..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_InvalidClientSecret {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_InvalidClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant specified cannot be found..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_InvalidTenantId {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_InvalidTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh snap! We are having issues connecting to Azure. Please try again..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_NoInternet {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string AzureEnvironment_China {
            get {
                return ResourceManager.GetString("AzureEnvironment_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string AzureEnvironment_German {
            get {
                return ResourceManager.GetString("AzureEnvironment_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string AzureEnvironment_Global {
            get {
                return ResourceManager.GetString("AzureEnvironment_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Government.
        /// </summary>
        internal static string AzureEnvironment_USGovernment {
            get {
                return ResourceManager.GetString("AzureEnvironment_USGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        internal static string Cluster {
            get {
                return ResourceManager.GetString("Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string ClusterMasterPage_NamespaceLabel {
            get {
                return ResourceManager.GetString("ClusterMasterPage_NamespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find the selected cluster, it may be deleted. Please select another cluster..
        /// </summary>
        internal static string ClusterNotFound_Message {
            get {
                return ResourceManager.GetString("ClusterNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster not found.
        /// </summary>
        internal static string ClusterNotFound_Title {
            get {
                return ResourceManager.GetString("ClusterNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ClustersPage_Accounts_Delete_MenuItemText {
            get {
                return ResourceManager.GetString("ClustersPage_Accounts_Delete_MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ClustersPage_Accounts_Edit_MenuItemText {
            get {
                return ResourceManager.GetString("ClustersPage_Accounts_Edit_MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string ClustersPage_AddAccount_ToolbarItem {
            get {
                return ResourceManager.GetString("ClustersPage_AddAccount_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        internal static string ClustersPage_Title {
            get {
                return ResourceManager.GetString("ClustersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle view.
        /// </summary>
        internal static string ClustersPage_ViewToggle_ToolbarItem {
            get {
                return ResourceManager.GetString("ClustersPage_ViewToggle_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last heartbeat time.
        /// </summary>
        internal static string ConditionDetailPage_LastHeartbeatTime {
            get {
                return ResourceManager.GetString("ConditionDetailPage_LastHeartbeatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last transition time.
        /// </summary>
        internal static string ConditionDetailPage_LastTransitionTime {
            get {
                return ResourceManager.GetString("ConditionDetailPage_LastTransitionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ConditionDetailPage_Message {
            get {
                return ResourceManager.GetString("ConditionDetailPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string ConditionDetailPage_Reason {
            get {
                return ResourceManager.GetString("ConditionDetailPage_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition detail.
        /// </summary>
        internal static string ConditionDetailPage_Title {
            get {
                return ResourceManager.GetString("ConditionDetailPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config and Storage.
        /// </summary>
        internal static string ConfigAndStorage {
            get {
                return ResourceManager.GetString("ConfigAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Maps.
        /// </summary>
        internal static string ConfigMaps {
            get {
                return ResourceManager.GetString("ConfigMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CronJobDetailPage_Details_ActiveJobCount {
            get {
                return ResourceManager.GetString("CronJobDetailPage_Details_ActiveJobCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrency Policy.
        /// </summary>
        internal static string CronJobDetailPage_Details_ConcurrencyPolicy {
            get {
                return ResourceManager.GetString("CronJobDetailPage_Details_ConcurrencyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Schedule.
        /// </summary>
        internal static string CronJobDetailPage_Details_LastSchedule {
            get {
                return ResourceManager.GetString("CronJobDetailPage_Details_LastSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string CronJobDetailPage_Details_Schedule {
            get {
                return ResourceManager.GetString("CronJobDetailPage_Details_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Deadline Seconds.
        /// </summary>
        internal static string CronJobDetailPage_Details_StartingDeadlineSeconds {
            get {
                return ResourceManager.GetString("CronJobDetailPage_Details_StartingDeadlineSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        internal static string CronJobDetailPage_Details_Suspend {
            get {
                return ResourceManager.GetString("CronJobDetailPage_Details_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron Jobs.
        /// </summary>
        internal static string CronJobs {
            get {
                return ResourceManager.GetString("CronJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon Sets.
        /// </summary>
        internal static string DaemonSets {
            get {
                return ResourceManager.GetString("DaemonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max surge: {0}, Max unavailable: {1}.
        /// </summary>
        internal static string DeploymentDetail_RollingUpdateStrategy {
            get {
                return ResourceManager.GetString("DeploymentDetail_RollingUpdateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated, {1} total, {2} available, {3} unavailable.
        /// </summary>
        internal static string DeploymentDetail_Status {
            get {
                return ResourceManager.GetString("DeploymentDetail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min ready seconds.
        /// </summary>
        internal static string DeploymentDetailPage_Details_MinReadySeconds {
            get {
                return ResourceManager.GetString("DeploymentDetailPage_Details_MinReadySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision history limit.
        /// </summary>
        internal static string DeploymentDetailPage_Details_RevisionHistoryLimit {
            get {
                return ResourceManager.GetString("DeploymentDetailPage_Details_RevisionHistoryLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling update strategy.
        /// </summary>
        internal static string DeploymentDetailPage_Details_RollingUpdateStrategy {
            get {
                return ResourceManager.GetString("DeploymentDetailPage_Details_RollingUpdateStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string DeploymentDetailPage_Details_Strategy {
            get {
                return ResourceManager.GetString("DeploymentDetailPage_Details_Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployments.
        /// </summary>
        internal static string Deployments {
            get {
                return ResourceManager.GetString("Deployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} running.
        /// </summary>
        internal static string Detail_Pods {
            get {
                return ResourceManager.GetString("Detail_Pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string DetailPage_Capacity {
            get {
                return ResourceManager.GetString("DetailPage_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string DetailPage_Capacity_Quantity {
            get {
                return ResourceManager.GetString("DetailPage_Capacity_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource name.
        /// </summary>
        internal static string DetailPage_Capacity_ResourceName {
            get {
                return ResourceManager.GetString("DetailPage_Capacity_ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string DetailPage_Conditions {
            get {
                return ResourceManager.GetString("DetailPage_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DetailPage_Data {
            get {
                return ResourceManager.GetString("DetailPage_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailPage_Details {
            get {
                return ResourceManager.GetString("DetailPage_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access modes.
        /// </summary>
        internal static string DetailPage_Details_AccessModes {
            get {
                return ResourceManager.GetString("DetailPage_Details_AccessModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        internal static string DetailPage_Details_Annotations {
            get {
                return ResourceManager.GetString("DetailPage_Details_Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        internal static string DetailPage_Details_CreationTime {
            get {
                return ResourceManager.GetString("DetailPage_Details_CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string DetailPage_Details_Images {
            get {
                return ResourceManager.GetString("DetailPage_Details_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string DetailPage_Details_Labels {
            get {
                return ResourceManager.GetString("DetailPage_Details_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DetailPage_Details_Name {
            get {
                return ResourceManager.GetString("DetailPage_Details_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string DetailPage_Details_Namespace {
            get {
                return ResourceManager.GetString("DetailPage_Details_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        internal static string DetailPage_Details_Pods {
            get {
                return ResourceManager.GetString("DetailPage_Details_Pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectors.
        /// </summary>
        internal static string DetailPage_Details_Selectors {
            get {
                return ResourceManager.GetString("DetailPage_Details_Selectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DetailPage_Details_Status {
            get {
                return ResourceManager.GetString("DetailPage_Details_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage class.
        /// </summary>
        internal static string DetailPage_Details_StorageClass {
            get {
                return ResourceManager.GetString("DetailPage_Details_StorageClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DetailPage_Details_Type {
            get {
                return ResourceManager.GetString("DetailPage_Details_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string DetailPage_Events {
            get {
                return ResourceManager.GetString("DetailPage_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery and Load Balancing.
        /// </summary>
        internal static string DiscoveryAndLoadBalancing {
            get {
                return ResourceManager.GetString("DiscoveryAndLoadBalancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to display here..
        /// </summary>
        internal static string EmptyMessage {
            get {
                return ResourceManager.GetString("EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string EventDetailPage_Count {
            get {
                return ResourceManager.GetString("EventDetailPage_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First seen.
        /// </summary>
        internal static string EventDetailPage_FirstSeen {
            get {
                return ResourceManager.GetString("EventDetailPage_FirstSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        internal static string EventDetailPage_LastSeen {
            get {
                return ResourceManager.GetString("EventDetailPage_LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string EventDetailPage_Message {
            get {
                return ResourceManager.GetString("EventDetailPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string EventDetailPage_Source {
            get {
                return ResourceManager.GetString("EventDetailPage_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-object.
        /// </summary>
        internal static string EventDetailPage_SubObject {
            get {
                return ResourceManager.GetString("EventDetailPage_SubObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event detail.
        /// </summary>
        internal static string EventDetailPage_Title {
            get {
                return ResourceManager.GetString("EventDetailPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Pod Autoscalers.
        /// </summary>
        internal static string HorizontalPodAutoscalers {
            get {
                return ResourceManager.GetString("HorizontalPodAutoscalers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresses.
        /// </summary>
        internal static string Ingresses {
            get {
                return ResourceManager.GetString("Ingresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} active, {1} succeeded, {2} failed.
        /// </summary>
        internal static string JobDetail_Status {
            get {
                return ResourceManager.GetString("JobDetail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completions.
        /// </summary>
        internal static string JobDetailPage_Details_Completions {
            get {
                return ResourceManager.GetString("JobDetailPage_Details_Completions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallelism.
        /// </summary>
        internal static string JobDetailPage_Details_Parallelism {
            get {
                return ResourceManager.GetString("JobDetailPage_Details_Parallelism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces.
        /// </summary>
        internal static string Namespaces {
            get {
                return ResourceManager.GetString("Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        internal static string NodeDetailPage_Details_Addresses {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        internal static string NodeDetailPage_Details_Architecture {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot ID.
        /// </summary>
        internal static string NodeDetailPage_Details_BootId {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_BootId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Runtime Version.
        /// </summary>
        internal static string NodeDetailPage_Details_ContainerRuntimeVersion {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_ContainerRuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel Version.
        /// </summary>
        internal static string NodeDetailPage_Details_KernelVersion {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_KernelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kubelet Version.
        /// </summary>
        internal static string NodeDetailPage_Details_KubeletVersion {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_KubeletVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KubeProxyVersion.
        /// </summary>
        internal static string NodeDetailPage_Details_KubeProxyVersion {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_KubeProxyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Id.
        /// </summary>
        internal static string NodeDetailPage_Details_MachineId {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_MachineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string NodeDetailPage_Details_OperatingSystem {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Image.
        /// </summary>
        internal static string NodeDetailPage_Details_OsImage {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_OsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pod CIDR.
        /// </summary>
        internal static string NodeDetailPage_Details_PodCidr {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_PodCidr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderID.
        /// </summary>
        internal static string NodeDetailPage_Details_ProviderId {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_ProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System UUID.
        /// </summary>
        internal static string NodeDetailPage_Details_SystemUuid {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_SystemUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unschedulable.
        /// </summary>
        internal static string NodeDetailPage_Details_Unschedulable {
            get {
                return ResourceManager.GetString("NodeDetailPage_Details_Unschedulable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes.
        /// </summary>
        internal static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are having connectivity issues doing that right now. Please try again..
        /// </summary>
        internal static string NoInternetErrorMessage {
            get {
                return ResourceManager.GetString("NoInternetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set..
        /// </summary>
        internal static string ObjectDetail_NotSet {
            get {
                return ResourceManager.GetString("ObjectDetail_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cluster doesn&apos;t support this object type. This maybe due to the version of Kubernetes installed; this application uses the 1.10 API..
        /// </summary>
        internal static string ObjectTypeNotSupportedMessage {
            get {
                return ResourceManager.GetString("ObjectTypeNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkAlertText {
            get {
                return ResourceManager.GetString("OkAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string PersistentVolumeClaimDetailPage_Details_Volume {
            get {
                return ResourceManager.GetString("PersistentVolumeClaimDetailPage_Details_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Volume Claims.
        /// </summary>
        internal static string PersistentVolumeClaims {
            get {
                return ResourceManager.GetString("PersistentVolumeClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        internal static string PersistentVolumeDetailPage_Details_Claim {
            get {
                return ResourceManager.GetString("PersistentVolumeDetailPage_Details_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string PersistentVolumeDetailPage_Details_Message {
            get {
                return ResourceManager.GetString("PersistentVolumeDetailPage_Details_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string PersistentVolumeDetailPage_Details_Reason {
            get {
                return ResourceManager.GetString("PersistentVolumeDetailPage_Details_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reclaim policy.
        /// </summary>
        internal static string PersistentVolumeDetailPage_Details_ReclaimPolicy {
            get {
                return ResourceManager.GetString("PersistentVolumeDetailPage_Details_ReclaimPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Volumes.
        /// </summary>
        internal static string PersistentVolumes {
            get {
                return ResourceManager.GetString("PersistentVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        internal static string PodDetailPage_Containers {
            get {
                return ResourceManager.GetString("PodDetailPage_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Args.
        /// </summary>
        internal static string PodDetailPage_Containers_Args {
            get {
                return ResourceManager.GetString("PodDetailPage_Containers_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string PodDetailPage_Containers_Commands {
            get {
                return ResourceManager.GetString("PodDetailPage_Containers_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variables.
        /// </summary>
        internal static string PodDetailPage_Containers_EnvironmentVariables {
            get {
                return ResourceManager.GetString("PodDetailPage_Containers_EnvironmentVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string PodDetailPage_Containers_Image {
            get {
                return ResourceManager.GetString("PodDetailPage_Containers_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string PodDetailPage_CreatedBy {
            get {
                return ResourceManager.GetString("PodDetailPage_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string PodDetailPage_CreatedBy_Kind {
            get {
                return ResourceManager.GetString("PodDetailPage_CreatedBy_Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PodDetailPage_CreatedBy_Name {
            get {
                return ResourceManager.GetString("PodDetailPage_CreatedBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string PodDetailPage_Details_IpAddress {
            get {
                return ResourceManager.GetString("PodDetailPage_Details_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string PodDetailPage_Details_Node {
            get {
                return ResourceManager.GetString("PodDetailPage_Details_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QoS Class.
        /// </summary>
        internal static string PodDetailPage_Details_QoS {
            get {
                return ResourceManager.GetString("PodDetailPage_Details_QoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Volume Claims.
        /// </summary>
        internal static string PodDetailPage_PersistentVolumeClaims {
            get {
                return ResourceManager.GetString("PodDetailPage_PersistentVolumeClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        internal static string Pods {
            get {
                return ResourceManager.GetString("Pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica sets.
        /// </summary>
        internal static string ReplicaSets {
            get {
                return ResourceManager.GetString("ReplicaSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Controllers.
        /// </summary>
        internal static string ReplicationControllers {
            get {
                return ResourceManager.GetString("ReplicationControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Listing.
        /// </summary>
        internal static string ResourceListingPage_Title {
            get {
                return ResourceManager.GetString("ResourceListingPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets.
        /// </summary>
        internal static string Secrets {
            get {
                return ResourceManager.GetString("Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster IP.
        /// </summary>
        internal static string ServiceDetailPage_Details_ClusterIp {
            get {
                return ResourceManager.GetString("ServiceDetailPage_Details_ClusterIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External endpoints.
        /// </summary>
        internal static string ServiceDetailPage_Details_ExternalEndpoints {
            get {
                return ResourceManager.GetString("ServiceDetailPage_Details_ExternalEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal endpoints.
        /// </summary>
        internal static string ServiceDetailPage_Details_InternalEndpoints {
            get {
                return ResourceManager.GetString("ServiceDetailPage_Details_InternalEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label selector.
        /// </summary>
        internal static string ServiceDetailPage_Details_LabelSelector {
            get {
                return ResourceManager.GetString("ServiceDetailPage_Details_LabelSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Affinity.
        /// </summary>
        internal static string ServiceDetailPage_Details_SessionAffinity {
            get {
                return ResourceManager.GetString("ServiceDetailPage_Details_SessionAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Listing.
        /// </summary>
        internal static string SettingsPage_ResourceListing {
            get {
                return ResourceManager.GetString("SettingsPage_ResourceListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Cluster.
        /// </summary>
        internal static string SettingsPage_SwitchCluster {
            get {
                return ResourceManager.GetString("SettingsPage_SwitchCluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stateful Sets.
        /// </summary>
        internal static string StatefulSets {
            get {
                return ResourceManager.GetString("StatefulSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string StorageClassDetailPage_Details_Parameters {
            get {
                return ResourceManager.GetString("StorageClassDetailPage_Details_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioner.
        /// </summary>
        internal static string StorageClassDetailPage_Details_Provisioner {
            get {
                return ResourceManager.GetString("StorageClassDetailPage_Details_Provisioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View related persistent volumes.
        /// </summary>
        internal static string StorageClassDetailPage_ViewRelatedPersistentVolumes {
            get {
                return ResourceManager.GetString("StorageClassDetailPage_ViewRelatedPersistentVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Classes.
        /// </summary>
        internal static string StorageClasses {
            get {
                return ResourceManager.GetString("StorageClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View related horizontal pod autoscalers.
        /// </summary>
        internal static string ViewRelatedHorizontalPodAutoscalers {
            get {
                return ResourceManager.GetString("ViewRelatedHorizontalPodAutoscalers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View related jobs.
        /// </summary>
        internal static string ViewRelatedJobs {
            get {
                return ResourceManager.GetString("ViewRelatedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View related pods.
        /// </summary>
        internal static string ViewRelatedPods {
            get {
                return ResourceManager.GetString("ViewRelatedPods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View related replica sets..
        /// </summary>
        internal static string ViewRelatedReplicaSets {
            get {
                return ResourceManager.GetString("ViewRelatedReplicaSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View related services.
        /// </summary>
        internal static string ViewRelatedServices {
            get {
                return ResourceManager.GetString("ViewRelatedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workloads.
        /// </summary>
        internal static string Workloads {
            get {
                return ResourceManager.GetString("Workloads", resourceCulture);
            }
        }
    }
}
