//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KubeMob.Common.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KubeMob.Common.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure.
        /// </summary>
        internal static string AddAccountPage_AddAzureAccount_Btn {
            get {
                return ResourceManager.GetString("AddAccountPage_AddAzureAccount_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string AddAccountPage_Title {
            get {
                return ResourceManager.GetString("AddAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddAzureAccountPage_AddButton {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID is required..
        /// </summary>
        internal static string AddAzureAccountPage_ClientId_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_ClientId_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string AddAzureAccountPage_ClientId_Label {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_ClientId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a client ID.
        /// </summary>
        internal static string AddAzureAccountPage_ClientId_Placeholder {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_ClientId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is required..
        /// </summary>
        internal static string AddAzureAccountPage_ClientSecret_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_ClientSecret_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret.
        /// </summary>
        internal static string AddAzureAccountPage_ClientSecret_Label {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_ClientSecret_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a client secret.
        /// </summary>
        internal static string AddAzureAccountPage_ClientSecret_Placeholder {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_ClientSecret_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string AddAzureAccountPage_Environment_Label {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_Environment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a environment.
        /// </summary>
        internal static string AddAzureAccountPage_Environment_Title {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_Environment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details for a service principal that has access to resources in your Microsoft Azure account. You can find out more about Service Princpial by tapping on the info button..
        /// </summary>
        internal static string AddAzureAccountPage_Help {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string AddAzureAccountPage_Information_ToolbarItem {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_Information_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID is required..
        /// </summary>
        internal static string AddAzureAccountPage_TenantId_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_TenantId_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        internal static string AddAzureAccountPage_TenantId_Label {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_TenantId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tenant ID.
        /// </summary>
        internal static string AddAzureAccountPage_TenantId_Placeholder {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_TenantId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Microsoft Azure.
        /// </summary>
        internal static string AddAzureAccountPage_Title {
            get {
                return ResourceManager.GetString("AddAzureAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kubemob.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client specified cannot be found..
        /// </summary>
        internal static string AzureAccountManager_IsValidCredentials_InvalidClientId {
            get {
                return ResourceManager.GetString("AzureAccountManager_IsValidCredentials_InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is invalid..
        /// </summary>
        internal static string AzureAccountManager_IsValidCredentials_InvalidClientSecret {
            get {
                return ResourceManager.GetString("AzureAccountManager_IsValidCredentials_InvalidClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant specified cannot be found..
        /// </summary>
        internal static string AzureAccountManager_IsValidCredentials_InvalidTenantId {
            get {
                return ResourceManager.GetString("AzureAccountManager_IsValidCredentials_InvalidTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh snap! We are having issues connecting to Azure. Please try again..
        /// </summary>
        internal static string AzureAccountManager_IsValidCredentials_NoInternet {
            get {
                return ResourceManager.GetString("AzureAccountManager_IsValidCredentials_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string AzureEnvironment_China {
            get {
                return ResourceManager.GetString("AzureEnvironment_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string AzureEnvironment_German {
            get {
                return ResourceManager.GetString("AzureEnvironment_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string AzureEnvironment_Global {
            get {
                return ResourceManager.GetString("AzureEnvironment_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Government.
        /// </summary>
        internal static string AzureEnvironment_USGovernment {
            get {
                return ResourceManager.GetString("AzureEnvironment_USGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        internal static string ClusterMaster_Pods {
            get {
                return ResourceManager.GetString("ClusterMaster_Pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string ClustersPage_AddAccount_ToolbarItem {
            get {
                return ResourceManager.GetString("ClustersPage_AddAccount_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        internal static string ClustersPage_Title {
            get {
                return ResourceManager.GetString("ClustersPage_Title", resourceCulture);
            }
        }
    }
}
