//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KubeMob.Common.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KubeMob.Common.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears there is something wrong with the account we are using to connect to this cluster. Please check the account details.
        /// </summary>
        internal static string AccountInvalid_Message {
            get {
                return ResourceManager.GetString("AccountInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account issue.
        /// </summary>
        internal static string AccountInvalid_Title {
            get {
                return ResourceManager.GetString("AccountInvalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure.
        /// </summary>
        internal static string AddAccountPage_AddAzureAccount_Btn {
            get {
                return ResourceManager.GetString("AddAccountPage_AddAzureAccount_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string AddAccountPage_Title {
            get {
                return ResourceManager.GetString("AddAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID is required..
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientId_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientId_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientId_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a client ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientId_Placeholder {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is required..
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientSecret_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientSecret_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientSecret_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientSecret_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a client secret.
        /// </summary>
        internal static string AddEditAzureAccountPage_ClientSecret_Placeholder {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_ClientSecret_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string AddEditAzureAccountPage_Environment_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Environment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a environment.
        /// </summary>
        internal static string AddEditAzureAccountPage_Environment_Title {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Environment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details for a service principal that has access to resources in your Microsoft Azure account. You can find out more about Service Princpial by tapping on the info button..
        /// </summary>
        internal static string AddEditAzureAccountPage_Help {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string AddEditAzureAccountPage_Information_ToolbarItem {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Information_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddEditAzureAccountPage_SaveButton {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID is required..
        /// </summary>
        internal static string AddEditAzureAccountPage_TenantId_IsNotNullOrEmptyRule_Message {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_TenantId_IsNotNullOrEmptyRule_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_TenantId_Label {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_TenantId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tenant ID.
        /// </summary>
        internal static string AddEditAzureAccountPage_TenantId_Placeholder {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_TenantId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure account.
        /// </summary>
        internal static string AddEditAzureAccountPage_Title {
            get {
                return ResourceManager.GetString("AddEditAzureAccountPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kubemob.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be a problem with this account.  Please update..
        /// </summary>
        internal static string AzureAccountManager_GetClusters_AuthenticationErrorMessage {
            get {
                return ResourceManager.GetString("AzureAccountManager_GetClusters_AuthenticationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing account already exists for this tenant..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_DuplicateTenantId {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_DuplicateTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client specified cannot be found..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_InvalidClientId {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_InvalidClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client secret is invalid..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_InvalidClientSecret {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_InvalidClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant specified cannot be found..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_InvalidTenantId {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_InvalidTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh snap! We are having issues connecting to Azure. Please try again..
        /// </summary>
        internal static string AzureAccountManager_TryAddCredentials_NoInternet {
            get {
                return ResourceManager.GetString("AzureAccountManager_TryAddCredentials_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        internal static string AzureEnvironment_China {
            get {
                return ResourceManager.GetString("AzureEnvironment_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string AzureEnvironment_German {
            get {
                return ResourceManager.GetString("AzureEnvironment_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string AzureEnvironment_Global {
            get {
                return ResourceManager.GetString("AzureEnvironment_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Government.
        /// </summary>
        internal static string AzureEnvironment_USGovernment {
            get {
                return ResourceManager.GetString("AzureEnvironment_USGovernment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config and Storage.
        /// </summary>
        internal static string ClusterMasterViewModel_ConfigAndStorage {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_ConfigAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Maps.
        /// </summary>
        internal static string ClusterMasterViewModel_ConfigAndStorage_ConfigMaps {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_ConfigAndStorage_ConfigMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Volume Claims.
        /// </summary>
        internal static string ClusterMasterViewModel_ConfigAndStorage_PersistentVolumeClaims {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_ConfigAndStorage_PersistentVolumeClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets.
        /// </summary>
        internal static string ClusterMasterViewModel_ConfigAndStorage_Secrets {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_ConfigAndStorage_Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery and Load Balancing.
        /// </summary>
        internal static string ClusterMasterViewModel_DiscoveryAndLoadBalancing {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_DiscoveryAndLoadBalancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresses.
        /// </summary>
        internal static string ClusterMasterViewModel_DiscoveryAndLoadBalancing_Ingresses {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_DiscoveryAndLoadBalancing_Ingresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ClusterMasterViewModel_DiscoveryAndLoadBalancing_Services {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_DiscoveryAndLoadBalancing_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string ClusterMasterViewModel_Overview {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workloads.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron Jobs.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_CronJobs {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_CronJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon Sets.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_DaemonSets {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_DaemonSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployments.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_Deployments {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_Deployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_Jobs {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_Pods {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_Pods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica sets.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_ReplicaSets {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_ReplicaSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Controllers.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_ReplicationControllers {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_ReplicationControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stateful Sets.
        /// </summary>
        internal static string ClusterMasterViewModel_Workloads_StatefulSets {
            get {
                return ResourceManager.GetString("ClusterMasterViewModel_Workloads_StatefulSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find the selected cluster, it may be deleted. Please select another cluster..
        /// </summary>
        internal static string ClusterNotFound_Message {
            get {
                return ResourceManager.GetString("ClusterNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster not found.
        /// </summary>
        internal static string ClusterNotFound_Title {
            get {
                return ResourceManager.GetString("ClusterNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ClustersPage_Accounts_Delete_MenuItemText {
            get {
                return ResourceManager.GetString("ClustersPage_Accounts_Delete_MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ClustersPage_Accounts_Edit_MenuItemText {
            get {
                return ResourceManager.GetString("ClustersPage_Accounts_Edit_MenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        internal static string ClustersPage_AddAccount_ToolbarItem {
            get {
                return ResourceManager.GetString("ClustersPage_AddAccount_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account contains no clusters..
        /// </summary>
        internal static string ClustersPage_Clusters_EmptyGroupMessage {
            get {
                return ResourceManager.GetString("ClustersPage_Clusters_EmptyGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here right now. Add an account..
        /// </summary>
        internal static string ClustersPage_Clusters_NoAccountsMessage {
            get {
                return ResourceManager.GetString("ClustersPage_Clusters_NoAccountsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        internal static string ClustersPage_Title {
            get {
                return ResourceManager.GetString("ClustersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle view.
        /// </summary>
        internal static string ClustersPage_ViewToggle_ToolbarItem {
            get {
                return ResourceManager.GetString("ClustersPage_ViewToggle_ToolbarItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no config maps..
        /// </summary>
        internal static string ConfigMapsPage_NoConfigMapsMessage {
            get {
                return ResourceManager.GetString("ConfigMapsPage_NoConfigMapsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Maps.
        /// </summary>
        internal static string ConfigMapsPage_Title {
            get {
                return ResourceManager.GetString("ConfigMapsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cron jobs..
        /// </summary>
        internal static string CronJobsPage_NoCronJobsMessage {
            get {
                return ResourceManager.GetString("CronJobsPage_NoCronJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cron Jobs.
        /// </summary>
        internal static string CronJobsPage_Title {
            get {
                return ResourceManager.GetString("CronJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no daemon sets..
        /// </summary>
        internal static string DaemonSetsPage_NoDaemonSetsMessage {
            get {
                return ResourceManager.GetString("DaemonSetsPage_NoDaemonSetsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daemon Sets.
        /// </summary>
        internal static string DaemonSetsPage_Title {
            get {
                return ResourceManager.GetString("DaemonSetsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no deployments..
        /// </summary>
        internal static string Deployments_NoDeploymentsMessage {
            get {
                return ResourceManager.GetString("Deployments_NoDeploymentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployments.
        /// </summary>
        internal static string DeploymentsPage_Title {
            get {
                return ResourceManager.GetString("DeploymentsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no ingresses..
        /// </summary>
        internal static string IngressesPage_NoIngressesMessage {
            get {
                return ResourceManager.GetString("IngressesPage_NoIngressesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresses.
        /// </summary>
        internal static string IngressesPage_Title {
            get {
                return ResourceManager.GetString("IngressesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no jobs..
        /// </summary>
        internal static string JobsPage_NoJobsMessage {
            get {
                return ResourceManager.GetString("JobsPage_NoJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string JobsPage_Title {
            get {
                return ResourceManager.GetString("JobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are having connectivity issues doing that right now. Please try again..
        /// </summary>
        internal static string NoInternetErrorMessage {
            get {
                return ResourceManager.GetString("NoInternetErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cluster doesn&apos;t support this object type. This maybe due to the version of Kubernetes installed; this application uses the 1.10 API..
        /// </summary>
        internal static string ObjectTypeNotSupportedMessage {
            get {
                return ResourceManager.GetString("ObjectTypeNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OkAlertText {
            get {
                return ResourceManager.GetString("OkAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no persistent volume claims..
        /// </summary>
        internal static string PersistentVolumeClaimsPage_NoServicesMessage {
            get {
                return ResourceManager.GetString("PersistentVolumeClaimsPage_NoServicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent Volume Claims.
        /// </summary>
        internal static string PersistentVolumeClaimsPage_Title {
            get {
                return ResourceManager.GetString("PersistentVolumeClaimsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no pods..
        /// </summary>
        internal static string PodsPage_NoPodsMessage {
            get {
                return ResourceManager.GetString("PodsPage_NoPodsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        internal static string PodsPage_Title {
            get {
                return ResourceManager.GetString("PodsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no replica sets..
        /// </summary>
        internal static string ReplicaSets_NoReplicaSetsMessage {
            get {
                return ResourceManager.GetString("ReplicaSets_NoReplicaSetsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica sets.
        /// </summary>
        internal static string ReplicaSetsPage_Title {
            get {
                return ResourceManager.GetString("ReplicaSetsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no replication controllers..
        /// </summary>
        internal static string ReplicationControllersPage_NoReplicationControllersMessage {
            get {
                return ResourceManager.GetString("ReplicationControllersPage_NoReplicationControllersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Controllers.
        /// </summary>
        internal static string ReplicationControllersPage_Title {
            get {
                return ResourceManager.GetString("ReplicationControllersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no secrets..
        /// </summary>
        internal static string SecretsPage_NoSecretsMessage {
            get {
                return ResourceManager.GetString("SecretsPage_NoSecretsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets.
        /// </summary>
        internal static string SecretsPage_Title {
            get {
                return ResourceManager.GetString("SecretsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no services..
        /// </summary>
        internal static string ServicesPage_NoServicesMessage {
            get {
                return ResourceManager.GetString("ServicesPage_NoServicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServicesPage_Title {
            get {
                return ResourceManager.GetString("ServicesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no stateful sets..
        /// </summary>
        internal static string StatefulSetsPage_NoServicesMessage {
            get {
                return ResourceManager.GetString("StatefulSetsPage_NoServicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stateful Sets.
        /// </summary>
        internal static string StatefulSetsPage_Title {
            get {
                return ResourceManager.GetString("StatefulSetsPage_Title", resourceCulture);
            }
        }
    }
}
